export const SET_BALANCE = 'SET_BALANCE';
export const DEPOSIT = 'DEPOSIT';
export const WITHDRAW = 'WITHDRAW';
export const FETCH_BITCOIN = 'FETCH_BITCOIN';
export const FETCH_ETHEREUM = 'FETCH_ETHEREUM';
export const FETCH_CRYPTO_NAMES = 'FETCH_CRYPTO_NAMES';
export const FETCH_SELECTED_CRYPTO = 'FETCH_SELECTED_CRYPTO';
